"""empty message

Revision ID: 72335906381b
Revises: 54d7fae7f636
Create Date: 2024-05-09 23:18:02.372485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72335906381b'
down_revision = '54d7fae7f636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('join', schema=None) as batch_op:
        batch_op.add_column(sa.Column('joins_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'frequency', ['joins_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('join', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('joins_id')

    # ### end Alembic commands ###
