"""empty message

Revision ID: a1f49797e458
Revises: adb7b1199028
Create Date: 2024-05-09 21:54:15.196773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1f49797e458'
down_revision = 'adb7b1199028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('join', schema=None) as batch_op:
        batch_op.add_column(sa.Column('joins_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'frequency', ['joins_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('join', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('joins_id')

    # ### end Alembic commands ###
