"""empty message

Revision ID: d5562ad400b7
Revises: 72335906381b
Create Date: 2024-05-10 09:13:38.680700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5562ad400b7'
down_revision = '72335906381b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.Text(), nullable=False))
        batch_op.create_unique_constraint(None, ['img'])
        batch_op.drop_column('myfile')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('myfile', sa.TEXT(), server_default=sa.text("'default.jpg'"), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('img')

    # ### end Alembic commands ###
